//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day11AssignmentsFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardInfo
    {
        public int Card_No { get; set; }
        public System.DateTime expdate { get; set; }
        public string cvvno { get; set; }
        public decimal balance { get; set; }
    }
}
